language: r
sudo: required
cache: packages

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - wget http://archive.apache.org/dist/lucene/solr/5.4.1/solr-5.4.1.tgz
  - tar -zxf solr-5.4.1.tgz
  - cd solr-5.4.1
  - bin/solr start -p 8983
  - bin/solr create -c gettingstarted -p 8983
  - bin/post -c gettingstarted example/exampledocs/*.xml
  - cd ../

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
      secure: K0pppSYESNGYdlG3OsjjyJRboEGdcxsl6GxjbHvJE7EsxKTJ5mH506tv6YjeXUcYRJ76D5G1UoKV/sCDC5/Bfz6RpDTAkuzOQyIlAatjuFKSAvx1G+y/PZjaGywb3cBZhYO93oG2TbAehMlXpIAnQcptc3YqhmocJrItnsU9T0M=
