language: r

env:
  matrix:
  - SOLR_VER=4.10.2
  - SOLR_VER=5.0.0
  - SOLR_VER=5.1.0
  - SOLR_VER=5.4.0

before_script:
  - case "$SOLR_VER" in
    "") ;;

    "4.10.2")
      export SOLR_VER=4.10.2 ;
      curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=SOLR_VER bash
      ;;

    "5.0.0")
      export SOLR_VER=5.0.0 ;
      curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=SOLR_VER bash
      ;;

    "5.1.0")
      export SOLR_VER=5.1.0 ;
      curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=SOLR_VER bash
      ;;

    "5.4.0")
      export SOLR_VER=5.4.0 ;
      curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=SOLR_VER bash
      ;;
   esac

r_github_packages:
- jimhester/covr

after_success:
- Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
      secure: K0pppSYESNGYdlG3OsjjyJRboEGdcxsl6GxjbHvJE7EsxKTJ5mH506tv6YjeXUcYRJ76D5G1UoKV/sCDC5/Bfz6RpDTAkuzOQyIlAatjuFKSAvx1G+y/PZjaGywb3cBZhYO93oG2TbAehMlXpIAnQcptc3YqhmocJrItnsU9T0M=
